# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b59e06b193054e8f2ab891a8b533130dbc1cce06bf2f25444989f5a882e0e1d105999c1d4f9253d8ba38574400056f3e36d13056d2f9664d0fff9610c6d1c827

test:
  secret_key_base: c72d546f961f2551870167c7b6b7776ba81c9bdb16b6cf9d92f7dc8f882a7ff75aced447ab185c7c03fa5c5170ac78e6cfa603f072058a30a9e5527a88286215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
